---
title: "GapminderAnalysis"
author: "Keagan Moo"
date: "1/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Repository

```{r}

download.file(url = "https://raw.githubusercontent.com/swcarpentry/r-novice-gapminder/gh-pages/_episodes_rmd/data/gapminder_data.csv", destfile = "data/gapminder_data.csv")

gapminder <- read.csv("data/gapminder_data.csv")
```

```{r}
getwd()
head(gapminder)
gapminder[gapminder$country == "China",]
dim(gapminder)
```


## \#plotting

### How does life expectancy change with GDP per capita???
```{r}
library(ggplot2)
ggplot(data = gapminder, mapping = aes(x=gdpPercap, y=lifeExp))

```


```{r}
ggplot(data = gapminder, mapping = aes(x=gdpPercap, y=lifeExp, color = continent)) + 
  geom_point(size = 0.5, alpha = 0.4) +
  scale_x_log10() +
  geom_smooth(method = "lm", size = 1) +
  theme_bw()

```


### How does life expectancy change per year????

```{r}
ggplot(data = gapminder, mapping = aes(x=year, y=lifeExp, by = country)) +
  geom_line(aes(color = continent)) +
  #scale_color_manual(values = c("red", "gray", "gray", "gray", "gray")) +
  geom_point(alpha = 0.2, size = 0.5) +
  theme_bw()


```


### How does life expectancy change in the Americas

```{r}
lifeExp_plot <- ggplot(data = gapminder[gapminder$continent == "Americas",], mapping = aes(x=year, y=lifeExp)) +
  geom_line() +
  facet_wrap(~country) +
  theme(axis.text.x = element_text(angle = 45), panel.background = element_rect(fill = 'white'), panel.grid.major = element_line(color = "gray"))

lifeExp_plot
```


```{r}
ggsave(plot=lifeExp_plot, file = "EATU.png")

```
